services:
  redis:
    image: redis:latest
    restart: always

  nginx:
    image: nginx:latest
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./Ateliware-challenge-client/dist:/etc/nginx/html
    environment:
      - VITE_API_TARGET=http://localhost:80
    ports:
      - "80:80"
    depends_on:
      - nodeserver

  nodeserver:
    build: ./Ateliware-challenge-server
    restart: always
    volumes:
      - ./Ateliware-challenge-server:/app
      - ./Ateliware-challenge-server/dist:/app/dist
    command: npm start
    ports:
      - 3000:3000
    environment:
      - PORT=3000
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
