version: '3'
services:
  redis:
    image: redis:latest
    restart: always

  nginx:
    build: ./Ateliware-challenge-client
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    environment:
      - VITE_API_TARGET_PORT=http://localhost:80
    expose:
      - 80
    ports:
      - "80:80"
    depends_on:
      - nodeserver

  nodeserver:
    build: ./Ateliware-challenge-server
    restart: always
    expose:
      - 3000
    environment:
      - PORT=3000
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
